# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f630f5aa908c96835388739b7fc0ca9b110c1d85efbb2c4a1f98415e6fff5571ba21fe3e34a89673bf0a3d4f59a7a25a8d0b2c9e7081a58503e5b0df870ce7d

test:
  secret_key_base: c16e641192221638a4e8aeff99edf88201aba9c2ae2012f887e593317ee76eed7f6c9412e610ce9062c6d308d92f3924f256e6af69d7056ebbadd49afcb1bc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
